# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    body_listener: true
    param_fetcher_listener: force
    body_converter:
        enabled: true
        validate: true
    format_listener:
        rules:
            prefer_extension: false
            fallback_format: json
    routing_loader:
        default_format: json
        include_format: false
    view:
        view_response_listener:
            enabled: true
    serializer:
        serialize_null: true
    exception:
        enabled: true
        exception_controller: 'App\Controller\ExceptionController::showAction'