# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    body_converter:
        enabled: true
    format_listener: true
    routing_loader:
        default_format: json
        include_format: false
    view:
        view_response_listener:
            enabled: true
    serializer:
        serialize_null: true
