fos_user:
    db_driver: orm
    firewall_name: api
    user_class: App\Entity\UserEntity
    group:
        group_class: App\Entity\GroupEntity
    from_email:
        address: info@housearatus.space
        sender_name: House Aratus