fos_rest:
    body_listener: true
    param_fetcher_listener: force
    body_converter:
        enabled: true
        validate: true
    format_listener:
        rules:
            prefer_extension: false
            fallback_format: json
    routing_loader:
        default_format: json
        include_format: false
    exception:
        enabled: true
        exception_controller: 'App\Controller\ExceptionController::showAction'