framework:
    secret: '%env(APP_SECRET)%'
    session:
        handler_id: ~
    php_errors:
        log: true
    templating:
        engines: ['php']
    cache:
        app: cache.adapter.redis
        default_redis_provider: redis://redis
