ldap_tools:
    general:
        schema_folder: "%kernel.root_dir%/Resources/LdapToolsBundle/schema"
        schema_format: yml
    domains:
        housearatus:
            domain_name: housearatus.space
            username: cn=admin,dc=housearatus,dc=space
            password: H8rat@us
            base_dn: "dc=housearatus,dc=space"
            servers: ["ldap.housearatus.space"]
            ldap_type: openldap
            use_ssl: true
            port: 636
    security:
        user: App\Entity\User