security:
    encoders:
        App\Entity\UserEntity: bcrypt
    providers:
        user_provider:
            id: App\Provider\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api_doc:
            pattern:  ^/doc
            stateless: true
            anonymous: true
        api_login:
            pattern:  ^/login
            stateless: true
            anonymous: true
        api_register:
            pattern: ^/register
            anonymous: true
        sso_login:
            pattern: ^/sso/login
            anonymous: true
        sso_callback:
            pattern: ^/sso/callback
            anonymous: true
        api:
            pattern: '[^/]'
            stateless: true
            provider: user_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
    access_control:
        - { path: ^/doc,           role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login,         role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login/refresh, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register,      role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/sso/login,     role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/sso/callback,  role: IS_AUTHENTICATED_ANONYMOUSLY }
