security:
    encoders:
        App\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        ldap:
            id: ldap_tools.security.user.ldap_user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api_login:
          pattern:  ^/login
          stateless: true
          anonymous: true
          guard:
              authenticators:
                  - ldap_tools.security.ldap_guard_authenticator
        api_register:
            pattern: ^/register
            anonymous: true
        sso_login:
            pattern: ^/sso/login
            anonymous: true
        sso_callback:
            pattern: ^/sso/callback
            anonymous: true
        api:
            pattern:   ^/
            stateless: true
            provider: ldap
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/register,      role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login,         role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/sso/login,     role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/sso/callback,  role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,              role: IS_AUTHENTICATED_FULLY }
