version: '2'
services:
    php-fpm:
        build: docker/php-fpm
        container_name: harat-php-fpm
        volumes:
            - ./:/var/www/symfony
            - ./docker/logs/symfony:/var/www/symfony/var/log

    nginx:
          image: nginx:alpine
          container_name: harat-nginx
          working_dir: /var/www/symfony
          ports:
           - "8000:80"
          links:
              - php-fpm
          volumes_from:
              - php-fpm
          volumes:
              - ./docker/logs/nginx/:/var/log/nginx
              - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

    elk:
        image: willdurand/elk
        container_name: harat-elk
        ports:
            - "8001:80"
        volumes:
            - ./docker/elk/logstash:/etc/logstash:cached
            - ./docker/elk/logstash/patterns:/opt/logstash/patterns:cached
        volumes_from:
            - php-fpm
            - nginx
