version: '2'
services:
  php-fpm:
    build: docker/php-fpm
    container_name: harat-php-fpm
    links:
      - redis
    volumes:
      - ./:/var/www/symfony:cached
      - ./docker/logs/symfony:/var/www/symfony/var/log:cached
  nginx:
    image: nginx:alpine
    container_name: harat-nginx
    working_dir: /var/www/symfony
    ports:
      - "8000:80"
    links:
      - php-fpm
    volumes_from:
      - php-fpm
    volumes:
      - ./docker/logs/nginx/:/var/log/nginx:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
  redis:
    image: redis
    ports:
      - "6379:6379"
  elk:
    image: willdurand/elk
    container_name: harat-elk
    ports:
        - "8002:80"
    volumes:
        - ./docker/elk/logstash:/etc/logstash:cached
        - ./docker/elk/logstash/patterns:/opt/logstash/patterns:cached
    volumes_from:
        - php-fpm
        - nginx
