parameters:
    locale: 'en'
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
    app.event.api_exception_listener:
        class: App\EventListener\ApiExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
    app.event.jwt_listener:
        class: App\EventListener\JWTListener
        tags:
          - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }
    App\Repository\BaseRepository:
        autowire: false
        arguments: ['@Symfony\Bridge\Doctrine\RegistryInterface', 'BaseRepository']
    App\Controller\BaseController:
        arguments: ['@request_stack']
    App\Response\BaseResponse:
        arguments: ['@request_stack']
    App\ArgumentResolver\BaseArgumentResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }